# Generated by Django 6.0.5 on 2026-08-25 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_devicelatestmetric_devicemetric_dm_ts_dev_key_idx_and_more'),
        ('producer', '0008_generatortype_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Hausspeicher', max_length=100)),
                ('capacity_kwh', models.DecimalField(decimal_places=2, default=10.0, help_text='Nennkapazität des Batteriespeichers in kWh', max_digits=8)),
                ('max_charge_power_kw', models.DecimalField(decimal_places=2, default=5.0, help_text='Max. Ladeleistung in kW', max_digits=8)),
                ('max_discharge_power_kw', models.DecimalField(decimal_places=2, default=5.0, help_text='Max. Entladeleistung in kW', max_digits=8)),
                ('min_soc_reserve_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Notstromreserve / Tiefentladeschutz in %', max_digits=5)),
                ('max_soc_pct', models.DecimalField(decimal_places=2, default=100.0, help_text='Maximales Ladelimit in %', max_digits=5)),
                ('charge_efficiency_pct', models.DecimalField(decimal_places=2, default=95.0, help_text='Ladewirkungsgrad in %', max_digits=5)),
                ('discharge_efficiency_pct', models.DecimalField(decimal_places=2, default=95.0, help_text='Entladewirkungsgrad in %', max_digits=5)),
                ('soc_metric_key', models.CharField(blank=True, default='soc', help_text='Datenpunkt für Ladestand (z. B. soc, battery_soc)', max_length=100)),
                ('power_metric_key', models.CharField(blank=True, default='power', help_text='Datenpunkt für Lade-/Entladeleistung (z. B. power, battery_power, battery_w)', max_length=100)),
                ('charge_energy_metric_key', models.CharField(blank=True, default='energy_in', max_length=100)),
                ('discharge_energy_metric_key', models.CharField(blank=True, default='energy_out', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('is_auto_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_energy_device', models.ForeignKey(blank=True, help_text='Gerät für kumulierten Ladezähler in kWh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_charge_energy_systems', to='devices.device')),
                ('discharge_energy_device', models.ForeignKey(blank=True, help_text='Gerät für kumulierten Entladezähler in kWh', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_discharge_energy_systems', to='devices.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_systems', to='devices.home')),
                ('power_device', models.ForeignKey(blank=True, help_text='Gerät, das die Lade-/Entladeleistung liefert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_power_systems', to='devices.device')),
                ('primary_device', models.ForeignKey(blank=True, help_text='Optionales Hauptgerät (z. B. Hybrid-Wechselrichter)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_storage_systems', to='devices.device')),
                ('soc_device', models.ForeignKey(blank=True, help_text='Gerät, das den Ladestand (SoC %) liefert', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_soc_systems', to='devices.device')),
            ],
            options={
                'verbose_name': 'Speichersystem',
                'verbose_name_plural': 'Speichersysteme',
                'ordering': ['name'],
            },
        ),
    ]
