# Generated by Django 6.0.5 on 2026-08-30 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_devicebaselineprofile'),
        ('producer', '0009_storagesystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagesystem',
            name='current_device',
            field=models.ForeignKey(blank=True, help_text='Optionales Gerät für Batteriestrom (in A) zur Vorzeichen-/Flussrichtungsbestimmung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_current_systems', to='devices.device'),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='current_metric_key',
            field=models.CharField(blank=True, default='battery_current', help_text='Datenpunkt für Batteriestrom in Ampere (z. B. battery_current, current)', max_length=100),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='voltage_device',
            field=models.ForeignKey(blank=True, help_text='Optionales Gerät für Batteriespannung (in V)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_voltage_systems', to='devices.device'),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='voltage_metric_key',
            field=models.CharField(blank=True, default='battery_voltage', help_text='Datenpunkt für Batteriespannung in Volt (z. B. battery_voltage, voltage)', max_length=100),
        ),
        migrations.AlterField(
            model_name='storagesystem',
            name='power_device',
            field=models.ForeignKey(blank=True, help_text='Gerät, das die Lade-/Entladeleistung liefert (in W)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_power_systems', to='devices.device'),
        ),
    ]
