# Generated by Django 6.0.5 on 2026-09-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer', '0010_storagesystem_current_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagesystem',
            name='control_mode',
            field=models.CharField(choices=[('self_consumption', 'PV-Autarkie (Autonom)'), ('price_optimized', 'Dynamisch / Preisgeführt (EPEX Spot / Tibber)'), ('forced_charge', 'Manuelle Zwangsladung'), ('forced_discharge', 'Manuelle Zwangsentladung'), ('idle', 'Standby / Ladesperre')], default='self_consumption', help_text='Aktiver Betriebsmodus des Speichersystems', max_length=30),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='ems_control_enabled',
            field=models.BooleanField(default=False, help_text='Aktive Speichersteuerung durch Sharegy EMS freischalten'),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='last_control_command',
            field=models.CharField(blank=True, default='', help_text='Zuletzt gesendeter Steuerbefehl (z. B. forced_charge 5000W)', max_length=100),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='last_controlled_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt des letzten gesendeten Steuerbefehls', null=True),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='price_threshold_ct',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Preisschwelle in ct/kWh (Netzladung aktiv wenn Börsenpreis <= Schwelle)', max_digits=6),
        ),
        migrations.AddField(
            model_name='storagesystem',
            name='target_charge_power_kw',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Soll-Ladeleistung bei aktiver Netzladung in kW', max_digits=6),
        ),
    ]
