# Generated by Django 6.0.5 on 2026-08-26 00:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free (Kostenlos)'), ('pro_monthly', 'Sharegy Pro (Monatlich - 4,99 €)'), ('pro_yearly', 'Sharegy Pro (Jährlich - 49,99 €)'), ('landlord_monthly', 'Vermieter & Quartiere (Monatlich - 14,99 €)'), ('landlord_yearly', 'Vermieter & Quartiere (Jährlich - 149,99 €)')], default='free', max_length=32)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('trialing', 'Testphase'), ('past_due', 'Zahlung ausstehend'), ('canceled', 'Gekündigt'), ('unpaid', 'Unbezahlt')], default='active', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(default='stripe', max_length=30)),
                ('payment_method_brand', models.CharField(blank=True, max_length=30)),
                ('payment_method_last4', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ems_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_ems_subscription',
            },
        ),
        migrations.CreateModel(
            name='EMSInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('amount_net_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_gross_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate_pct', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Bezahlt'), ('open', 'Offen'), ('refunded', 'Erstattet')], default='paid', max_length=20)),
                ('payment_method', models.CharField(default='Kreditkarte (via Stripe)', max_length=50)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('street_and_number', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='DE', max_length=50)),
                ('vat_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ems_invoices', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.emssubscription')),
            ],
            options={
                'db_table': 'billing_ems_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emssubscription',
            index=models.Index(fields=['user', 'status'], name='billing_ems_user_id_9fc609_idx'),
        ),
        migrations.AddIndex(
            model_name='emssubscription',
            index=models.Index(fields=['plan', 'status'], name='billing_ems_plan_9c1812_idx'),
        ),
        migrations.AddIndex(
            model_name='emsinvoice',
            index=models.Index(fields=['user', '-created_at'], name='billing_ems_user_id_fcd166_idx'),
        ),
        migrations.AddIndex(
            model_name='emsinvoice',
            index=models.Index(fields=['invoice_number'], name='billing_ems_invoice_aa2227_idx'),
        ),
    ]
