# Generated by Django 6.0.5 on 2026-08-29 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_emssubscription_emsinvoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Prozentualer Rabatt (%)'), ('fixed_amount', 'Fester Rabattbetrag (€)'), ('free_months', 'Gratismonate')], default='free_months', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('free_plan', models.CharField(default='pro_monthly', max_length=32)),
                ('duration_months', models.PositiveIntegerField(default=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(default=100)),
                ('redemptions_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_coupon',
                'indexes': [models.Index(fields=['code', 'is_active'], name='billing_cou_code_ea633c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_discount', models.CharField(blank=True, max_length=255)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.coupon')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.emssubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_coupon_redemption',
                'ordering': ['-redeemed_at'],
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
