# Generated by Django 6.0.5 on 2026-09-01 01:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usertermsconsent'),
        ('billing', '0003_coupon_couponredemption'),
        ('core', '0005_tenant_button_color_tenant_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard Sharing Tarif', max_length=150)),
                ('sharing_price_ct_kwh', models.DecimalField(decimal_places=2, default=12.0, help_text='Bezugspreis für geteilten Solarstrom (Cent/kWh)', max_digits=6)),
                ('producer_payout_ct_kwh', models.DecimalField(decimal_places=2, default=10.0, help_text='Vergütung für geteilten Solarstrom an Einspeiser (Cent/kWh)', max_digits=6)),
                ('community_fee_ct_kwh', models.DecimalField(decimal_places=2, default=2.0, help_text='Betriebsumlage der Energy Community (Cent/kWh)', max_digits=6)),
                ('grid_fee_saved_ct_kwh', models.DecimalField(decimal_places=2, default=0.0, help_text='Ermäßigte Netzentgelte gem. § 42b EnWG (Cent/kWh)', max_digits=6)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_tariffs', to='core.tenant')),
            ],
            options={
                'db_table': 'billing_community_tariff',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMonthlyStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement_number', models.CharField(max_length=64, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('produced_total_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('consumed_total_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('shared_imported_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('shared_exported_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('grid_residual_import_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('grid_residual_export_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('charge_shared_import_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit_shared_export_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('community_fee_eur', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_balance_eur', models.DecimalField(decimal_places=2, default=0.0, help_text='Netto-Saldo: Positiv = Gutschrift/Auszahlung, Negativ = Nachzahlung', max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('finalized', 'Abgerechnet'), ('settled', 'Ausgeglichen')], default='draft', max_length=20)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_statements', to='accounts.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_statements', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_statements', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statements', to='billing.communitytariff')),
            ],
            options={
                'db_table': 'billing_community_monthly_statement',
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communitytariff',
            index=models.Index(fields=['tenant', 'is_active'], name='billing_com_tenant__27874b_idx'),
        ),
        migrations.AddIndex(
            model_name='communitytariff',
            index=models.Index(fields=['tenant', 'valid_from'], name='billing_com_tenant__f44f24_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymonthlystatement',
            index=models.Index(fields=['tenant', 'period_start'], name='billing_com_tenant__105738_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymonthlystatement',
            index=models.Index(fields=['user', 'period_start'], name='billing_com_user_id_f90e57_idx'),
        ),
        migrations.AddIndex(
            model_name='communitymonthlystatement',
            index=models.Index(fields=['statement_number'], name='billing_com_stateme_bc6497_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='communitymonthlystatement',
            unique_together={('membership', 'period_start', 'period_end')},
        ),
    ]
