# Generated by Django 6.0.5 on 2026-09-01 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usertermsconsent'),
        ('billing', '0005_communityannouncement'),
        ('core', '0005_tenant_button_color_tenant_primary_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytariff',
            name='allocation_model',
            field=models.CharField(choices=[('dynamic', 'Dynamisch nach Verbrauch (Standard)'), ('static', 'Statische Beteiligungsquoten (MEA)'), ('hybrid', 'Hybrid (Vorrang-Quote + dynamischer Überlauf)')], default='dynamic', help_text='Verfahren zur Verteilung von Solarstrom innerhalb der Gemeinschaft', max_length=20),
        ),
        migrations.CreateModel(
            name='CommunityMemberShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_percent', models.DecimalField(decimal_places=4, default=0.0, help_text='Beteiligungsquote an der Gemeinschafts-PV in Prozent (%)', max_digits=7)),
                ('mea_numerator', models.PositiveIntegerField(blank=True, help_text='Miteigentumsanteile Zähler (z. B. 250)', null=True)),
                ('mea_denominator', models.PositiveIntegerField(default=1000, help_text='Miteigentumsanteile Nenner (Standard 1000 oder 10.000)')),
                ('assigned_kwp', models.DecimalField(blank=True, decimal_places=3, help_text='Zugewiesener kWp-Anteil an der Gemeinschaftsanlage', max_digits=8, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='accounts.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_shares', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_community_member_share',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='billing_com_tenant__fd9b6c_idx'), models.Index(fields=['membership', 'is_active'], name='billing_com_members_7f6f8f_idx'), models.Index(fields=['user', 'is_active'], name='billing_com_user_id_8936ca_idx')],
            },
        ),
    ]
