# Generated by Django 6.0.5 on 2026-09-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_communitytariff_allocation_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitytariff',
            name='feed_in_spot_share_pct',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Prozentuale Beteiligung des Einspeisers am Börsenpreis (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='communitytariff',
            name='pricing_model',
            field=models.CharField(choices=[('static', 'Statischer Festpreis'), ('spot_indexed', 'Börsenpreis-indexiert (EPEX Spot Day-Ahead)'), ('time_of_use', 'Dynamischer Zeittarif (HT/NT)')], default='static', help_text='Preismechanismus: Festpreis, EPEX Spotmarkt-Indexierung oder Zeittarif', max_length=30),
        ),
        migrations.AddField(
            model_name='communitytariff',
            name='spot_cap_price_ct_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximalpreisobergrenze / Preisbremse in Cent/kWh (Cap)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='communitytariff',
            name='spot_floor_price_ct_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Mindestpreisuntergrenze in Cent/kWh (Floor)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='communitytariff',
            name='spot_markup_ct_kwh',
            field=models.DecimalField(decimal_places=2, default=3.5, help_text='Aufschlag auf den EPEX Spotpreis in Cent/kWh (z. B. +3,50 Ct)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='communitytariff',
            name='sharing_price_ct_kwh',
            field=models.DecimalField(decimal_places=2, default=12.0, help_text='Bezugspreis für geteilten Solarstrom (Cent/kWh) im statischen Modell', max_digits=6),
        ),
    ]
