# Generated by Django 6.0.5 on 2026-09-17 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_communitytariff_feed_in_spot_share_pct_and_more'),
        ('core', '0008_tenant_legal_form_tenant_max_shares_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('street', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='DE', max_length=50)),
                ('meter_malo_id', models.CharField(blank=True, default='', help_text='11-stellige Marktlokations-ID (MaLo) des Zählers für 15m-Allokation', max_length=50)),
                ('participant_role', models.CharField(choices=[('prosumer', 'Prosumer (Einspeiser)'), ('consumer', 'Consumer (Abnehmer)'), ('both', 'Beides')], default='consumer', max_length=20)),
                ('shares_count', models.PositiveIntegerField(default=1)),
                ('share_nominal_value_eur', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('total_amount_eur', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('statute_accepted', models.BooleanField(default=True)),
                ('statute_version_accepted', models.CharField(default='1.0', max_length=50)),
                ('statute_accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('statute_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Wartet auf Vorstandsbeschluss'), ('approved', 'Vom Vorstand genehmigt'), ('rejected', 'Abgelehnt'), ('withdrawn', 'Zurückgezogen')], default='pending_approval', max_length=30)),
                ('member_number', models.CharField(blank=True, default='', help_text='Fortlaufende Mitgliedsnummer im Mitgliederverzeichnis gem. § 30 GenG', max_length=50)),
                ('board_approved_at', models.DateTimeField(blank=True, null=True)),
                ('board_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cooperative_applications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperative_applications', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cooperative_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_cooperative_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='billing_coo_tenant__607e2c_idx'), models.Index(fields=['email'], name='billing_coo_email_5fde6e_idx')],
            },
        ),
    ]
