# Generated by Django 6.0.5 on 2026-08-30 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_devicelatestmetric_devicemetric_dm_ts_dev_key_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceBaselineProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appliance_type', models.CharField(choices=[('bwwp', 'Brauchwasserwärmepumpe (BWWP)'), ('heatpump', 'Heizungs-Wärmepumpe'), ('fridge', 'Kühlschrank / Gefriergerät'), ('circulation_pump', 'Zirkulationspumpe'), ('heating_pump', 'Umwälz- / Heizungspumpe'), ('washing_machine', 'Waschmaschine / Trockner'), ('dishwasher', 'Geschirrspüler'), ('ev_charger', 'Wallbox / E-Auto'), ('ac_inverter', 'Klimaanlage / Inverter'), ('generic', 'Individuelles Gerät')], default='generic', max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text='Überwachung der Baseline aktiv')),
                ('standby_power_w', models.FloatField(default=30.0, help_text='Erwarteter Standby-/Ruheverbrauch in Watt (z. B. 30W bei BWWP)')),
                ('standby_tolerance_pct', models.FloatField(default=30.0, help_text='Zulässige Abweichung vom Standby in % (z. B. 30%)')),
                ('standby_max_w', models.FloatField(default=45.0, help_text='Absolute Obergrenze für den Standby-Zustand (z. B. 45W)')),
                ('operating_power_min_w', models.FloatField(default=350.0, help_text='Minimale Leistung im aktiven Betriebsmodus (z. B. 350W)')),
                ('operating_power_max_w', models.FloatField(default=750.0, help_text='Maximale Leistung im regulären Betriebsmodus (z. B. 750W)')),
                ('max_continuous_run_hours', models.FloatField(default=6.0, help_text='Maximal zulässige ununterbrochene Laufzeit vor Alarm (z. B. 6.0h)')),
                ('learning_mode', models.BooleanField(default=False, help_text='Lernt automatisch die Baseline aus den realen Messwerten')),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('current_health_status', models.CharField(choices=[('healthy', 'Normal / Baseline eingehalten'), ('warning', 'Auffällig / Leichte Abweichung'), ('anomaly', 'Kritische Anomalie / Alarm')], default='healthy', max_length=20)),
                ('last_measured_standby_w', models.FloatField(blank=True, null=True)),
                ('last_measured_operating_w', models.FloatField(blank=True, null=True)),
                ('anomaly_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_profile', to='devices.device')),
            ],
        ),
    ]
