# Generated by Django 6.0.5 on 2026-09-01 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_devicebaselineprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudDeviceIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.CharField(help_text='ID des YAML-Profils (z. B. sungrow_isolarcloud, solaredge_cloud)', max_length=64)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Konfigurations- und Zugangsdaten (z. B. appkey, user_account, password, site_id)')),
                ('polling_interval_seconds', models.IntegerField(default=60, help_text='Abfrageintervall in Sekunden (Standard: 60s)')),
                ('is_active', models.BooleanField(default=True, help_text='Aktiviert das periodische Polling über Celery')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('ok', 'Aktiv / Verbunden'), ('error', 'Fehler bei Abfrage'), ('pending', 'Ausstehend')], default='pending', max_length=20)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_integration', to='devices.device')),
            ],
        ),
    ]
