# Generated by Django 6.0.5 on 2026-09-03 02:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_clouddeviceintegration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingRfidTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_tag', models.CharField(help_text='Eindeutige UID der RFID-Karte', max_length=64, unique=True)),
                ('name', models.CharField(default='Mein RFID-Chip', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_tags', to='devices.home')),
                ('user', models.ForeignKey(blank=True, help_text='Zugeordneter Nutzer für Kostenabrechnung', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFID-Ladechip',
                'verbose_name_plural': 'RFID-Ladechips',
            },
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_point_id', models.CharField(db_index=True, help_text='Eindeutige OCPP ChargePoint-Kennung', max_length=64, unique=True)),
                ('name', models.CharField(default='Wallbox', max_length=120)),
                ('vendor', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Verfügbar'), ('Preparing', 'Fahrzeug verbunden'), ('Charging', 'Lädt aktiv'), ('SuspendedEVSE', 'Pausiert (Station)'), ('SuspendedEV', 'Pausiert (Fahrzeug voll)'), ('Finishing', 'Ladevorgang beendet'), ('Reserved', 'Reserviert'), ('Unavailable', 'Nicht verfügbar'), ('Faulted', 'Fehler / Störung')], db_index=True, default='Available', max_length=32)),
                ('error_code', models.CharField(blank=True, default='NoError', max_length=64)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('connectors_count', models.PositiveIntegerField(default=1)),
                ('phases', models.PositiveIntegerField(choices=[(1, '1-phasig'), (3, '3-phasig')], default=3)),
                ('max_current_a', models.FloatField(default=16.0, help_text='Maximaler Ladestrom je Phase in A (z.B. 16A = 11kW, 32A = 22kW)')),
                ('min_current_a', models.FloatField(default=6.0, help_text='Minimaler Ladestrom nach IEC 61851 (Standard 6A)')),
                ('smart_charging_mode', models.CharField(choices=[('pv_surplus', '☀️ Nur Solarüberschuss'), ('min_pv', '⛅ Min + PV-Überschuss'), ('spot_price', '💶 Börsenpreisgeführt'), ('instant', '⚡ Sofortladen (Max. Power)'), ('off', '🛑 Gesperrt / Pausiert')], default='pv_surplus', max_length=32)),
                ('price_threshold_ct', models.FloatField(default=15.0, help_text='Preisschwelle in ct/kWh für börsenpreisgeführtes Laden')),
                ('min_soc_target_pct', models.PositiveIntegerField(default=50, help_text='Mindest-Ziel-SoC, bis zu dem unabhängig vom Sonnenstand geladen wird')),
                ('active_power_w', models.FloatField(default=0.0, help_text='Aktuelle Ladeleistung in Watt')),
                ('current_l1', models.FloatField(default=0.0, help_text='Strom L1 in Ampere')),
                ('current_l2', models.FloatField(default=0.0, help_text='Strom L2 in Ampere')),
                ('current_l3', models.FloatField(default=0.0, help_text='Strom L3 in Ampere')),
                ('voltage_v', models.FloatField(default=230.0, help_text='Spannung in Volt')),
                ('target_current_a', models.FloatField(default=0.0, help_text='Aktueller Soll-Ladestrom je Phase')),
                ('active_transaction_id', models.IntegerField(blank=True, null=True)),
                ('session_energy_kwh', models.FloatField(default=0.0, help_text='Geladene Energie der aktuellen Session in kWh')),
                ('total_energy_kwh', models.FloatField(default=0.0, help_text='Gesamter Zählerstand der Wallbox in kWh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_stations', to='devices.home')),
            ],
            options={
                'verbose_name': 'OCPP Ladestation',
                'verbose_name_plural': 'OCPP Ladestationen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.IntegerField(db_index=True)),
                ('id_tag', models.CharField(blank=True, default='', help_text='RFID Tag / Auth ID', max_length=64)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('meter_start_wh', models.FloatField(default=0.0)),
                ('meter_stop_wh', models.FloatField(blank=True, null=True)),
                ('total_energy_kwh', models.FloatField(default=0.0)),
                ('solar_energy_kwh', models.FloatField(default=0.0, help_text='Anteil kostenloser Sonnenstrom')),
                ('grid_energy_kwh', models.FloatField(default=0.0, help_text='Anteil zugekaufter Netzstrom')),
                ('solar_coverage_pct', models.FloatField(default=0.0, help_text='Prozentualer PV-Anteil')),
                ('cost_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gesamtkosten für Community-Abrechnung', max_digits=8)),
                ('stop_reason', models.CharField(blank=True, default='Local', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Abgeschlossen'), ('aborted', 'Abgebrochen')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='devices.chargingstation')),
            ],
            options={
                'verbose_name': 'Ladesitzung',
                'verbose_name_plural': 'Ladesitzungen',
                'ordering': ['-start_time'],
            },
        ),
    ]
