# Generated by Django 6.0.5 on 2026-09-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_chargingrfidtag_chargingstation_chargingsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddeviceintegration',
            name='polling_interval_seconds',
            field=models.IntegerField(default=15, help_text='Abfrageintervall in Sekunden (Standard: 15s)'),
        ),
    ]
