# Generated by Django 6.0.5 on 2026-09-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_alter_clouddeviceintegration_polling_interval_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='reservation_expiry',
            field=models.DateTimeField(blank=True, help_text='Ablaufzeitpunkt der Reservierung', null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='reservation_id',
            field=models.IntegerField(blank=True, help_text='Aktive Reservierungs-ID', null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='reserved_id_tag',
            field=models.CharField(blank=True, default='', help_text='RFID Tag / Auth ID der Reservierung', max_length=64),
        ),
    ]
