# Generated by Django 6.0.5 on 2026-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0042_chargingstation_reservation_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='composite_schedule_data',
            field=models.JSONField(blank=True, help_text='Letzter empfangener zusammengesetzter Ladefahrplan', null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='diagnostics_status',
            field=models.CharField(blank=True, default='Idle', help_text='Status des Diagnostics-Uploads', max_length=32),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='last_diagnostics_file',
            field=models.CharField(blank=True, default='', help_text='Name der letzten Diagnosedatei', max_length=255),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='local_auth_list_version',
            field=models.IntegerField(default=0, help_text='Version der lokalen Offline-Auth-Liste auf der Box'),
        ),
    ]
