# Generated by Django 6.0.5 on 2026-09-08 21:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_chargingstation_composite_schedule_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingsession',
            name='v2g_discharged_kwh',
            field=models.FloatField(default=0.0, help_text='Ins Haus / Netz entladene Energie in kWh'),
        ),
        migrations.AddField(
            model_name='chargingsession',
            name='v2g_earnings_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Erwirtschafteter Ertrag aus V2G-Börsenarbitrage / V2H-Einsparung', max_digits=8),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='device_variables',
            field=models.JSONField(blank=True, default=dict, help_text='Gespeicherte Device-Model-Variablen (OCPP 2.0.1/2.1)'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='ev_battery_capacity_kwh',
            field=models.FloatField(default=77.0, help_text='Brutto-Kapazität der Fahrzeugbatterie in kWh'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='ev_soc_pct',
            field=models.FloatField(blank=True, help_text='Aktueller State of Charge (SoC) des Elektroautos in %', null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='iso15118_emaid',
            field=models.CharField(blank=True, default='', help_text='ISO 15118 Contract eMAID (Plug & Charge)', max_length=128),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='iso15118_evccid',
            field=models.CharField(blank=True, default='', help_text='ISO 15118 EVCCID des Fahrzeugs', max_length=128),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='ocpp_version',
            field=models.CharField(choices=[('ocpp1.6', 'OCPP 1.6-J'), ('ocpp2.0.1', 'OCPP 2.0.1'), ('ocpp2.1', 'OCPP 2.1')], default='ocpp1.6', help_text='Aktive oder ausgehandelte OCPP Protokollversion', max_length=16),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='supports_bidirectional',
            field=models.BooleanField(default=False, help_text='Wallbox und Fahrzeug unterstützen bidirektionales Laden (V2G/V2H)'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='v2g_discharge_power_w',
            field=models.FloatField(default=0.0, help_text='Aktuelle Live-Entladeleistung in Watt'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='v2g_max_discharge_power_kw',
            field=models.FloatField(default=11.0, help_text='Max. Entladeleistung in kW für Haus- oder Netzeinspeisung'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='v2g_min_soc_pct',
            field=models.PositiveIntegerField(default=50, help_text='Sicherheits-Mindestladestand des Fahrzeugakkus in %'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='v2g_mode',
            field=models.CharField(choices=[('off', 'Aus / Nur Laden'), ('v2h_home', 'V2H Heimspeicher-Puffer'), ('v2g_grid', 'V2G Börsenstrom-Arbitrage'), ('v2x_auto', 'V2X Smart Auto')], default='off', help_text='Aktiver V2G/V2H Betriebsmodus', max_length=32),
        ),
    ]
