# Generated by Django 6.0.5 on 2026-09-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0044_chargingsession_v2g_discharged_kwh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='battery_care_mode',
            field=models.BooleanField(default=True, help_text='Schonendes Laden/Entladen zur Verlängerung der Batterielebensdauer'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Tägliche Abfahrtszeit für garantierte Mindestladung (z.B. 07:30)', null=True),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='max_c_rate',
            field=models.FloatField(default=0.5, help_text='Maximale Dauerentladerate bezogen auf die Akkukapazität (C-Rate)'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='peak_shaving_threshold_w',
            field=models.FloatField(default=4200.0, help_text='Netzbezugsschwelle in Watt für Peak Shaving Entladung'),
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='target_departure_soc_pct',
            field=models.PositiveIntegerField(default=80, help_text='Ziel-SoC zur Abfahrtszeit in %'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='v2g_mode',
            field=models.CharField(choices=[('off', 'Aus / Nur Laden'), ('v2h_home', 'V2H Heimspeicher-Puffer'), ('v2g_grid', 'V2G Börsenstrom-Arbitrage'), ('v2x_auto', 'V2X Smart Auto'), ('peak_shaving', '⚡ Peak Shaving (Lastspitzenkappung)')], default='off', help_text='Aktiver V2G/V2H Betriebsmodus', max_length=32),
        ),
    ]
