# Generated by Django 6.0.5 on 2026-09-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0045_chargingstation_battery_care_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouddeviceintegration',
            name='polling_interval_seconds',
            field=models.IntegerField(blank=True, default=None, help_text='Individuelles Abfrageintervall in Sekunden. Leer lassen, um das globale Hersteller-Intervall aus den EMS-Einstellungen zu nutzen.', null=True, verbose_name='Individueller Lesezyklus (Sekunden)'),
        ),
    ]
