# Generated by Django 6.0.5 on 2026-08-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meter_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='button_color',
            field=models.CharField(default='bg-orange-500', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='from-orange-400', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='to-orange-600', max_length=50),
        ),
    ]
