# Generated by Django 6.0.5 on 2026-09-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_button_color_tenant_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aggregatedreading',
            name='core_aggreg_meter_i_9ae3b2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedreading',
            unique_together={('meter', 'period_start', 'obis_code')},
        ),
        migrations.AddIndex(
            model_name='aggregatedreading',
            index=models.Index(fields=['meter', 'period_start', 'obis_code'], name='core_aggreg_meter_i_6ce62b_idx'),
        ),
    ]
