# Generated by Django 6.0.5 on 2026-09-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_aggregatedreading_core_aggreg_meter_i_9ae3b2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='accent_color',
            field=models.CharField(default='#6366F1', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='custom_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='favicon_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_whitelabel_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='button_color',
            field=models.CharField(default='bg-emerald-600', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#10B981', max_length=50),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='secondary_color',
            field=models.CharField(default='#059669', max_length=50),
        ),
    ]
