# Generated by Django 6.0.5 on 2026-09-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_accent_color_tenant_company_legal_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='legal_form',
            field=models.CharField(choices=[('cooperative', 'Eingetragene Genossenschaft (eG)'), ('association', 'Eingetragener Verein (e.V.)'), ('gmbh', 'GmbH / Bürger-GmbH & Co. KG'), ('weg', 'Wohnungseigentümergemeinschaft (WEG)'), ('landlord', 'Vermieter / Contractor')], default='cooperative', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_shares_count',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='min_shares_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenant',
            name='model_type',
            field=models.CharField(choices=[('mieterstrom', 'Mieterstrom (§ 42a EnWG Vollversorgung)'), ('ggv', 'Gemeinschaftliche Gebäudeversorgung (§ 42b EnWG)'), ('energy_sharing', 'Regionales Energy Sharing (Bürgerenergie / RED II)')], default='energy_sharing', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='share_nominal_value_eur',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='statute_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='statute_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='statute_version',
            field=models.CharField(blank=True, default='1.0', max_length=50),
        ),
    ]
