# Generated by Django 6.0.5 on 2026-08-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_remove_tenant_created_at_tenant_button_color_and_more'),
        ('tracking', '0002_alter_eventlog_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
