# Generated by Django 6.0.5 on 2026-08-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_spotpricedaysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='hometariff',
            name='feed_in_tariff_eur_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.082, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='hometariff',
            name='feed_in_tariff_type',
            field=models.CharField(choices=[('static', 'Feste EEG-Vergütung'), ('dynamic', 'Börsen-Marktwert Solar'), ('none', 'Keine Vergütung (Nulleinspeisung)')], default='static', max_length=20),
        ),
    ]
