# Generated by Django 6.0.5 on 2026-08-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0037_devicelatestmetric_devicemetric_dm_ts_dev_key_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_id', models.BigIntegerField(help_text='64-Bit Matter Fabric ID', unique=True)),
                ('controller_node_id', models.BigIntegerField(default=1, help_text='Node-ID des Sharegy Matter Controllers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matter_fabric', to='devices.home')),
            ],
            options={
                'verbose_name': 'Matter Fabric',
                'verbose_name_plural': 'Matter Fabrics',
            },
        ),
        migrations.CreateModel(
            name='MatterNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.BigIntegerField(help_text='Eindeutige Matter Node ID innerhalb der Fabric')),
                ('name', models.CharField(max_length=128)),
                ('device_type', models.CharField(choices=[('smart_plug', 'Smart Plug / Zwischenstecker (On/Off + Energy)'), ('evse', 'Matter EVSE / Wallbox'), ('solar_inverter', 'Solar-Wechselrichter / BKW'), ('battery', 'Batteriespeicher'), ('heatpump', 'Wärmepumpe'), ('meter', 'Stromzähler / Sub-Meter')], default='smart_plug', max_length=64)),
                ('device_type_id', models.IntegerField(default=266, help_text='Standard Matter Device Type ID (Hex)')),
                ('vendor_id', models.IntegerField(default=65521)),
                ('product_id', models.IntegerField(default=32769)),
                ('discriminator', models.IntegerField(default=3840)),
                ('setup_pin', models.CharField(blank=True, max_length=32)),
                ('manual_code', models.CharField(blank=True, max_length=32)),
                ('qr_payload', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('firmware_version', models.CharField(default='1.3.0', max_length=64)),
                ('attributes_payload', models.JSONField(blank=True, default=dict)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matter_node', to='devices.device')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='matter.matterfabric')),
            ],
            options={
                'verbose_name': 'Matter Node',
                'verbose_name_plural': 'Matter Nodes',
                'ordering': ['node_id'],
                'unique_together': {('fabric', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='MatterEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_id', models.IntegerField(default=1)),
                ('name', models.CharField(default='Endpoint 1', max_length=64)),
                ('device_type_id', models.IntegerField(default=266)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='matter.matternode')),
            ],
            options={
                'verbose_name': 'Matter Endpoint',
                'verbose_name_plural': 'Matter Endpoints',
                'unique_together': {('node', 'endpoint_id')},
            },
        ),
        migrations.CreateModel(
            name='MatterCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('cluster_name', models.CharField(max_length=128)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Aktuelle Cluster-Attribute (z. B. active_power, on_off, energy)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='matter.matterendpoint')),
            ],
            options={
                'verbose_name': 'Matter Cluster',
                'verbose_name_plural': 'Matter Clusters',
                'unique_together': {('endpoint', 'cluster_id')},
            },
        ),
    ]
