# Generated by Django 6.0.5 on 2026-08-26 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usersettings_language_usersettings_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
