# Generated by Django 6.0.5 on 2026-08-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_billing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platform_role',
            field=models.CharField(choices=[('system_admin', 'Systemadmin'), ('finance', 'Finanzen & Billing'), ('user_admin', 'Userverwaltung (Global)'), ('helpdesk', 'Plattform Helpdesk'), ('none', 'Keine Plattform-Rolle')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantinvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Energy Admin'), ('user_admin', 'Energy Userverwaltung'), ('helpdesk', 'Energy Helpdesk'), ('auditor', 'Kassenprüfer / Auditor'), ('member', 'Mitglied'), ('editor', 'Editor (Legacy)'), ('viewer', 'Viewer (Legacy)')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Energy Admin'), ('user_admin', 'Energy Userverwaltung'), ('helpdesk', 'Energy Helpdesk'), ('auditor', 'Kassenprüfer / Auditor'), ('member', 'Mitglied'), ('editor', 'Editor (Legacy)'), ('viewer', 'Viewer (Legacy)')], default='member', max_length=20),
        ),
    ]
