# Generated by Django 6.0.5 on 2026-08-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_billing_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='billing_name',
        ),
    ]
