# Generated by Django 6.0.5 on 2026-08-29 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_platform_role_alter_tenantinvite_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTermsConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(default='2026-08', max_length=32)),
                ('privacy_version', models.CharField(default='2026-08', max_length=32)),
                ('consent_type', models.CharField(choices=[('registration', 'Registrierung'), ('upgrade_pro', 'Pro/Landlord Upgrade'), ('terms_update', 'AGB-Aktualisierung')], default='registration', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_terms_consent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_8c5be4_idx')],
            },
        ),
    ]
