# Generated by Django 6.0.5 on 2026-09-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usertermsconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
