# Generated by Django 6.0.5 on 2026-09-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
