# Generated by Django 6.0.5 on 2026-09-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userprofile_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notify_critical_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='notify_weekly_report',
            field=models.BooleanField(default=True),
        ),
    ]
