# Generated by Django 6.0.5 on 2026-09-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usersettings_notify_critical_alerts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magiclogintoken',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
