# Generated by Django 6.0.5 on 2026-09-12 03:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_magiclogintoken_code'),
        ('devices', '0046_alter_clouddeviceintegration_polling_interval_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('street', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('website', models.URLField(blank=True, default='')),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('partner_tier', models.CharField(choices=[('certified', 'Zertifizierter Fachpartner'), ('gold', 'Gold Partner'), ('premium', 'Premium Fachbetrieb')], default='certified', max_length=30)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenantinvite',
            name='role',
            field=models.CharField(choices=[('admin', 'Energy Admin'), ('user_admin', 'Energy Userverwaltung'), ('helpdesk', 'Energy Helpdesk'), ('auditor', 'Kassenprüfer / Auditor'), ('installer', 'Fachpartner / Installateur'), ('member', 'Mitglied'), ('editor', 'Editor (Legacy)'), ('viewer', 'Viewer (Legacy)')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Energy Admin'), ('user_admin', 'Energy Userverwaltung'), ('helpdesk', 'Energy Helpdesk'), ('auditor', 'Kassenprüfer / Auditor'), ('installer', 'Fachpartner / Installateur'), ('member', 'Mitglied'), ('editor', 'Editor (Legacy)'), ('viewer', 'Viewer (Legacy)')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('pending', 'Ausstehend'), ('revoked', 'Widerrufen')], default='active', max_length=20)),
                ('allow_remote_control', models.BooleanField(default=True)),
                ('allow_telemetry_history', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_consents', to='devices.home')),
                ('partner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_homes', to='accounts.partnercompany')),
            ],
            options={
                'unique_together': {('home', 'partner_company')},
            },
        ),
        migrations.CreateModel(
            name='PartnerMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Betriebsleiter / Admin'), ('technician', 'Monteur / Servicetechniker'), ('viewer', 'Viewer')], default='technician', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.partnercompany')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'partner_company')},
            },
        ),
    ]
