# Generated by Django 6.0.5 on 2026-08-25 11:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Technischer Key (z. B. inverters, optimizer)', max_length=80, unique=True)),
                ('icon', models.CharField(default='📖', help_text='Emoji oder Icon-Name', max_length=20)),
                ('title_de', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_de', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hilfe-Kategorie',
                'verbose_name_plural': 'Hilfe-Kategorien',
                'ordering': ['sort_order', 'title_de'],
            },
        ),
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-Slug (z. B. solar-prognose-verstaendnis)', max_length=120, unique=True)),
                ('context_key', models.CharField(blank=True, db_index=True, help_text="Kontext-Schlüssel für Drawer-Matching (z. B. 'forecast', 'energy', 'tariffs', 'alerts', 'devices', 'optimizer')", max_length=50)),
                ('title_de', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('summary_de', models.TextField(blank=True, help_text='Kurzbeschreibung für Suchergebnisse und Drawer')),
                ('summary_en', models.TextField(blank=True)),
                ('content_de', models.TextField(help_text='Ausführlicher Artikelinhalt in Markdown (Deutsch)')),
                ('content_en', models.TextField(blank=True, help_text='Ausführlicher Artikelinhalt in Markdown (Englisch)')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Liste von Schlagworten für Volltextsuche')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Hervorheben auf der Wissensportal-Startseite')),
                ('sort_order', models.IntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('helpful_yes', models.PositiveIntegerField(default=0)),
                ('helpful_no', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='helpcenter.helpcategory')),
            ],
            options={
                'verbose_name': 'Hilfe-Artikel',
                'verbose_name_plural': 'Hilfe-Artikel',
                'ordering': ['sort_order', '-is_featured', '-created_at'],
            },
        ),
    ]
