# Generated by Django 6.0.5 on 2026-09-11 21:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPPDispatchOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dispatch_type', models.CharField(choices=[('positive_flex', 'Positive Flexibilität (Einspeisung ↑ / Last ↓)'), ('negative_flex', 'Negative Flexibilität (Einspeisung ↓ / Last ↑ / Speicher laden)')], default='positive_flex', max_length=30)),
                ('target_power_kw', models.DecimalField(decimal_places=2, help_text='Soll-Leistungsänderung in kW', max_digits=10)),
                ('duration_minutes', models.IntegerField(default=15, help_text='Dauer des Abrufs in Minuten')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('active', 'Aktiv / Erbringung läuft'), ('completed', 'Erfolgreich abgeschlossen'), ('failed', 'Fehlgeschlagen / Abweichung'), ('cancelled', 'Storniert')], default='pending', max_length=20)),
                ('requested_by', models.CharField(default='Übertragungsnetzbetreiber (ÜNB)', max_length=150)),
                ('connect_plus_order_id', models.CharField(blank=True, default='', help_text='Connect+ / Redispatch 2.0 Auftragsnummer', max_length=100)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('baseline_power_kw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Referenzleistung vor Aktivierung', max_digits=10)),
                ('delivered_power_kw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tatsächlich erbrachte mittlere Leistung', max_digits=10)),
                ('energy_delivered_kwh', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Erbringungsarbeit in kWh', max_digits=10)),
                ('remuneration_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Erlös / Vergütung in EUR', max_digits=10)),
                ('activated_devices_count', models.IntegerField(default=0)),
                ('meta_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPP Dispatch-Auftrag',
                'verbose_name_plural': 'VPP Dispatch-Aufträge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPPFlexibilityPool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='z. B. 50Hertz Heimspeicher-Pool Berlin', max_length=200)),
                ('tso_operator', models.CharField(choices=[('tennet', 'TenneT TSO'), ('50hertz', '50Hertz Transmission'), ('amprion', 'Amprion'), ('transnetbw', 'TransnetBW'), ('local_dso', 'Lokaler Verteilnetzbetreiber (VNB)')], default='50hertz', max_length=50)),
                ('market_product', models.CharField(choices=[('afrr_positive', 'aFRR Positive Sekundärregelleistung (+kW)'), ('afrr_negative', 'aFRR Negative Sekundärregelleistung (-kW)'), ('fcr', 'FCR Primärregelleistung (Frequenzhaltung +/-)'), ('redispatch_2_0', 'Redispatch 2.0 (Einspeisemanagement & Engpassbeseitigung)'), ('peak_shaving', 'Netzentgelt-Optimierung / Peak Shaving (§ 19 StromNEV)'), ('spot_arbitrage', 'Dynamische Intraday/Day-Ahead Arbitrage')], default='afrr_positive', max_length=50)),
                ('grid_region', models.CharField(blank=True, default='Regelzone Deutschland', max_length=100)),
                ('postal_code_prefix', models.CharField(default='*', help_text="Komma-separierte PLZ-Bereiche oder '*' für alle", max_length=100)),
                ('min_activation_power_kw', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('max_activation_power_kw', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPP Flexibilitäts-Pool',
                'verbose_name_plural': 'VPP Flexibilitäts-Pools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VPPDispatchTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('target_power_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measured_power_kw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency_hz', models.DecimalField(decimal_places=3, default=Decimal('50.000'), max_digits=6)),
                ('battery_soc_avg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_points', to='vpp.vppdispatchorder')),
            ],
            options={
                'verbose_name': 'VPP Dispatch Telemetrie',
                'verbose_name_plural': 'VPP Dispatch Telemetrien',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='vppdispatchorder',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_orders', to='vpp.vppflexibilitypool'),
        ),
    ]
