# Generated by Django 6.0.5 on 2026-09-16 03:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0046_alter_clouddeviceintegration_polling_interval_seconds'),
        ('vpp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPPAssetEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Aktiv / Bereit für Abrufe'), ('paused', 'Pausiert durch Nutzer'), ('opted_out', 'Abgemeldet')], default='active', max_length=20)),
                ('min_soc_reserve_pct', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Mindest-Ladestand, der für den Eigenbedarf im Haushalt reserviert bleibt (%)', max_digits=5)),
                ('payout_share_pct', models.DecimalField(decimal_places=2, default=Decimal('80.00'), help_text='Kunden-Anteil an der erlösten Flexibilitätsprämie (Standard: 80%)', max_digits=5)),
                ('total_earned_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_dispatches_count', models.IntegerField(default=0)),
                ('auto_spot_arbitrage', models.BooleanField(default=True, help_text='Erlaubt automatische Börsentarif-Arbitrage (Preistiefststände laden)')),
                ('auto_afrr_frequency', models.BooleanField(default=True, help_text='Erlaubt Teilnahme an Sekundärregelleistung (aFRR)')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpp_enrollments', to='devices.device')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_assets', to='vpp.vppflexibilitypool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpp_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPP Asset Einschreibung',
                'verbose_name_plural': 'VPP Asset Einschreibungen',
                'ordering': ['-joined_at'],
                'unique_together': {('user', 'device')},
            },
        ),
        migrations.CreateModel(
            name='VPPAssetDispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_power_kw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivered_power_kw', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('energy_kwh', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('gross_revenue_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer_payout_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sharegy_fee_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('soc_before_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('soc_after_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_cleared', models.BooleanField(default=False, help_text='Wurde bereits im monatlichen Clearing-Lauf abgerechnet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpp_dispatches', to='devices.device')),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_dispatches', to='vpp.vppdispatchorder')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_events', to='vpp.vppassetenrollment')),
            ],
            options={
                'verbose_name': 'VPP Asset Dispatch Allokation',
                'verbose_name_plural': 'VPP Asset Dispatch Allokationen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPPClearingStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('dispatches_count', models.IntegerField(default=0)),
                ('total_energy_kwh', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10)),
                ('gross_revenue_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('customer_payout_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sharegy_fee_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('credited', 'Als Guthaben auf Kundenkonto verbucht'), ('paid_out', 'Ausgezahlt (Stripe / Bank)')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpp_clearing_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPP Clearing Abrechnung',
                'verbose_name_plural': 'VPP Clearing Abrechnungen',
                'ordering': ['-period_end'],
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
