# Generated by Django 6.0.5 on 2026-08-25 02:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0037_devicelatestmetric_devicemetric_dm_ts_dev_key_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('no_pv', 'Keine PV-Erzeugung (Ertragsausfall)'), ('battery_empty', 'Batterie leer / Ungewöhnliche Entladung'), ('night_leakage', 'Unerwarteter Nachtverbrauch / Dauerlast'), ('device_offline', 'Gerät offline / Signal-Verlust'), ('negative_price', 'Negativer Strompreis / Börsentief-Chance'), ('price_peak', 'Extremer Preis-Peak (Dunkelflaute)'), ('grid_import_surplus', 'Netzbezug trotz Solarüberschuss'), ('freeze_guard', 'Frostschutz & Wärmepumpen-Vorlauf'), ('custom', 'Benutzerdefiniert')], max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Kritisch'), ('warning', 'Warnung'), ('info', 'Information / Spar-Tipp')], default='info', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_hint', models.CharField(blank=True, default='', max_length=255)),
                ('action_type', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('acknowledged', 'Gesehen / Quittiert'), ('resolved', 'Behoben / Gelöst')], db_index=True, default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_events', to='devices.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='devices.home')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['home', 'status', 'created_at'], name='alerts_aler_home_id_2a8bba_idx'), models.Index(fields=['home', 'alert_type', 'status'], name='alerts_aler_home_id_7677c2_idx')],
            },
        ),
    ]
