# Generated by Django 6.0.5 on 2026-08-28 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.CharField(db_index=True, default='global', max_length=50)),
                ('shortcut', models.SlugField(help_text="e.g. 'reboot-inverter', 'gateway-sync'")),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('body_de', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Textbaustein (Canned Response)',
                'verbose_name_plural': 'Textbausteine (Canned Responses)',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SupportProjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_key', models.SlugField(help_text="Unique slug: 'sharegy', 'factofy', etc.", unique=True)),
                ('name', models.CharField(help_text="Display name (e.g. 'Sharegy HEMS', 'Factofy Digital Twin')", max_length=100)),
                ('secret_key', models.CharField(default=uuid.uuid4, help_text='Shared secret key used to sign and verify external JWT tokens / API requests', max_length=128)),
                ('ticket_prefix', models.CharField(default='SUP', help_text='Prefix for ticket numbers, e.g. SHAR, FACT', max_length=10)),
                ('allowed_categories', models.JSONField(blank=True, default=list, help_text="List of allowed categories for this project, e.g. ['hardware', 'telemetry', 'billing']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Support-Projektkonfiguration',
                'verbose_name_plural': 'Support-Projektkonfigurationen',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('project_key', models.CharField(db_index=True, default='sharegy', max_length=50)),
                ('external_user_id', models.CharField(blank=True, db_index=True, help_text='External user ID from connected platform (e.g. Factofy usr_123)', max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, default='general', max_length=60)),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Normal'), ('high', 'Hoch'), ('urgent', 'Dringend / Kritisch')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Neu / Offen'), ('in_progress', 'In Bearbeitung'), ('waiting_customer', 'Wartet auf Rückmeldung'), ('waiting_internal', 'Wartet intern / Entwicklung'), ('resolved', 'Gelöst'), ('closed', 'Geschlossen')], db_index=True, default='open', max_length=30)),
                ('context_payload', models.JSONField(blank=True, default=dict, help_text='Arbitrary telemetry/asset metadata (e.g. device_id, building_id, sensor_eui, coordinates, url, browser)')),
                ('first_response_due', models.DateTimeField(blank=True, null=True)),
                ('first_responded_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support-Ticket',
                'verbose_name_plural': 'Support-Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(default='System', max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='support_desk.ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket-Aktivitätsprotokoll',
                'verbose_name_plural': 'Ticket-Aktivitätsprotokolle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_sender_name', models.CharField(blank=True, max_length=150)),
                ('external_sender_email', models.EmailField(blank=True, max_length=254)),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('is_internal_note', models.BooleanField(default=False, help_text='Internal note only visible to support team / staff agents.')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_support_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_desk.ticket')),
            ],
            options={
                'verbose_name': 'Ticket-Nachricht',
                'verbose_name_plural': 'Ticket-Nachrichten',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='support_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_desk.ticket')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support_desk.ticketmessage')),
            ],
            options={
                'verbose_name': 'Ticket-Anhang',
                'verbose_name_plural': 'Ticket-Anhänge',
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project_key', 'status'], name='support_des_project_2e9ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project_key', 'created_at'], name='support_des_project_3142f9_idx'),
        ),
    ]
