# Generated by Django 6.0.5 on 2026-09-14 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tenant_accent_color_tenant_company_legal_name_and_more'),
        ('support_desk', '0002_helpcategory_helparticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Zugeordneter Mandant / Partner-Community', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='core.tenant'),
        ),
    ]
