# Generated by Django 6.0.5 on 2026-09-01 05:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tenant_button_color_tenant_primary_color_and_more'),
        ('devices', '0038_devicebaselineprofile'),
        ('energy', '0004_emssignalsource_unique_home_device_signal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SteuVEDeviceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steuve_type', models.CharField(choices=[('heat_pump', 'Wärmepumpe'), ('wallbox', 'Wallbox (Ladeeinrichtung)'), ('battery_storage', 'Batteriespeicher (Netzladen)'), ('ac_cooling', 'Klimagerät / Raumkühlung')], default='wallbox', max_length=30)),
                ('rated_power_kw', models.DecimalField(decimal_places=2, default=Decimal('11.00'), help_text='Nennleistung in kW', max_digits=6)),
                ('minimum_power_kw', models.DecimalField(decimal_places=2, default=Decimal('1.40'), help_text='Minimale Dimmleistung (z. B. 1-phasig 6A = 1,4 kW)', max_digits=6)),
                ('priority', models.PositiveSmallIntegerField(default=2, help_text='1: Höchste Priorität (Wärme), 2: Speicher, 3: Nachrangig / Drosselbar (Wallbox)')),
                ('is_dimmable', models.BooleanField(default=True)),
                ('is_currently_dimmed', models.BooleanField(default=False)),
                ('current_power_limit_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steuve_config', to='devices.device')),
            ],
            options={
                'ordering': ['priority', '-rated_power_kw'],
            },
        ),
        migrations.CreateModel(
            name='GridDimmingSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('vnb_api', 'VNB Inbound REST API'), ('wmsb_cls', 'Smart Meter Gateway (CLS-Kanal)'), ('shelly_input', 'Shelly Koppelrelais Digital-Input'), ('manual_test', 'Manueller Test / Installateur-Audit')], default='vnb_api', max_length=30)),
                ('target_max_grid_kw', models.DecimalField(decimal_places=2, default=Decimal('4.20'), help_text='Maximal erlaubter Netzbezug in kW gem. § 14a EnWG', max_digits=6)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grid_dimming_signals', to='devices.home')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grid_dimming_signals', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grid_dimming_signals', to='core.tenant')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['is_active', 'started_at'], name='energy_grid_is_acti_d7ed05_idx'), models.Index(fields=['home', 'is_active'], name='energy_grid_home_id_17cba1_idx')],
            },
        ),
    ]
