# Generated by Django 6.0.5 on 2026-09-04 04:15

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_chargingrfidtag_chargingstation_chargingsession'),
        ('energy', '0005_steuvedeviceconfig_griddimmingsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BWWPLoadManagementConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, help_text='Aktiviert das automatische BWWP-Lastmanagement')),
                ('control_mode', models.CharField(choices=[('hybrid', 'Hybrid (PV-Überschuss & Günstige Börsenstunden)'), ('pv_surplus', 'Nur PV-Überschuss'), ('spot_price', 'Nur Börsenstrompreis (Spotmarkt)'), ('manual', 'Manuell (Keine Automatik)')], default='hybrid', max_length=20)),
                ('min_temp_c', models.DecimalField(decimal_places=1, default=Decimal('45.0'), help_text='Minimale Wohlfühltemperatur (°C) – darunter wird unabhängig vom Preis geheizt', max_digits=4)),
                ('target_temp_c', models.DecimalField(decimal_places=1, default=Decimal('52.0'), help_text='Standard-Solltemperatur (°C)', max_digits=4)),
                ('boost_temp_c', models.DecimalField(decimal_places=1, default=Decimal('60.0'), help_text='Erhöhte Solltemperatur für SG-Ready Boost (°C)', max_digits=4)),
                ('max_safety_temp_c', models.DecimalField(decimal_places=1, default=Decimal('65.0'), help_text='Absoluter Überhitzungsschutz (°C) – schaltet Relais sofort ab', max_digits=4)),
                ('min_pv_surplus_w', models.DecimalField(decimal_places=1, default=Decimal('800.0'), help_text='Mindest-PV-Überschuss (W) zur Aktivierung des SG-Ready Boost', max_digits=6)),
                ('max_price_threshold_ct', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Maximaler Strompreis (ct/kWh) für preisgesteuertes Heizen', max_digits=5)),
                ('battery_soc_reserve_pct', models.DecimalField(decimal_places=1, default=Decimal('50.0'), help_text='Mindest-Akkustand (%), bevor PV-Überschuss in die BWWP fließt', max_digits=4)),
                ('min_run_time_minutes', models.PositiveSmallIntegerField(default=20, help_text='Mindestlaufzeit (Minuten) nach dem Einschalten zum Verdichterschutz')),
                ('min_cooldown_minutes', models.PositiveSmallIntegerField(default=15, help_text='Mindestruhezeit (Minuten) nach dem Abschalten gegen Takten')),
                ('current_sg_state', models.CharField(choices=[('1_lock', 'Sperre / Standby'), ('2_normal', 'Normalbetrieb'), ('3_boost', 'SG-Ready Boost (Verstärkter Betrieb)'), ('4_force', 'Zwangsanlauf')], default='2_normal', max_length=20)),
                ('last_switched_at', models.DateTimeField(blank=True, null=True)),
                ('last_decision_reason', models.CharField(blank=True, default='', max_length=255)),
                ('manual_override_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bwwp_config', to='devices.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bwwp_configs', to='devices.home')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['home', 'active'], name='energy_bwwp_home_id_41a9da_idx')],
            },
        ),
    ]
