# Generated by Django 6.0.5 on 2026-09-04 04:31

import django.db.models.deletion
import django.utils.timezone
import energy.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0040_chargingrfidtag_chargingstation_chargingsession'),
        ('energy', '0006_bwwploadmanagementconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadPriorityConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('master_mode', models.CharField(choices=[('autopilot', 'Autopilot (KI, PV-Überschuss & Börsenpreise)'), ('pv_only', 'Nur PV-Überschuss (Maximale Autarkie)'), ('price_saver', 'Sparfuchs (Börsen-Tiefstpreise & Spotmarkt)'), ('manual', 'Manuell / Urlaub (Automatik pausiert)')], default='autopilot', max_length=20)),
                ('priority_order', models.JSONField(default=energy.models.default_priority_order, help_text='Reihenfolge der Lasten für die Zuteilung von PV-Überschuss und Schaltfenstern')),
                ('min_pv_headroom_w', models.DecimalField(decimal_places=1, default=Decimal('200.0'), help_text='Sicherheits-Reserve (W) beim Schalten von Zusatzlasten', max_digits=6)),
                ('auto_dispatch_enabled', models.BooleanField(default=True, help_text='Aktiviert die globale Dispatch-Engine für alle Verbraucher')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load_priority_config', to='devices.home')),
            ],
        ),
        migrations.CreateModel(
            name='LoadConsumerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('pool', 'Pool- & Filterpumpe'), ('ac', 'Klimaanlage / Raumkühlung'), ('appliances', 'Haushaltsgerät (Waschmaschine/Spüler)'), ('heating_rod', 'Heizstab / Power-to-Heat'), ('bwwp', 'Brauchwasserwärmepumpe'), ('wallbox', 'Wallbox / E-Auto'), ('battery', 'Heimspeicher'), ('other', 'Sonstiger flexibler Verbraucher')], default='pool', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('rated_power_w', models.DecimalField(decimal_places=1, default=Decimal('1000.0'), help_text='Typische Nennleistung in Watt', max_digits=7)),
                ('mode', models.CharField(choices=[('hybrid', 'Hybrid (Solar & Börsenpreis)'), ('pv_surplus', 'Nur Solarüberschuss'), ('spot_price', 'Nur Börsenpreise'), ('manual', 'Manuell')], default='hybrid', max_length=20)),
                ('min_daily_runtime_minutes', models.PositiveIntegerField(default=0, help_text='Garantierte tägliche Mindestlaufzeit (z. B. 300 Min für 5h Poolfilterung)')),
                ('daily_runtime_completed_minutes', models.PositiveIntegerField(default=0)),
                ('last_run_reset_date', models.DateField(default=django.utils.timezone.now)),
                ('custom_settings', models.JSONField(blank=True, default=dict, help_text='Kategoriespezifische Parameter (z.B. pre_cool_delta_c, ready_to_start)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_consumer_configs', to='devices.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_consumers', to='devices.home')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['home', 'category'], name='energy_load_home_id_555058_idx')],
            },
        ),
    ]
