# Generated by Django on 2026-09-07

import uuid
from decimal import Decimal
from django.db import migrations, models


def seed_initial_ems_settings(apps, schema_editor):
    EMSGlobalSettings = apps.get_model("energy", "EMSGlobalSettings")
    InverterManufacturerPollingConfig = apps.get_model("energy", "InverterManufacturerPollingConfig")

    if not EMSGlobalSettings.objects.exists():
        EMSGlobalSettings.objects.create(
            default_grid_price_ct_kwh=Decimal("32.00"),
            default_feed_in_tariff_ct_kwh=Decimal("8.20"),
            default_spot_markup_ct_kwh=Decimal("1.50"),
            battery_arbitrage_min_spread_ct_kwh=Decimal("8.00"),
            community_sharing_price_ct_kwh=Decimal("12.00"),
            community_producer_payout_ct_kwh=Decimal("10.00"),
            community_platform_fee_ct_kwh=Decimal("2.00"),
            grid_fee_ct_kwh=Decimal("9.5000"),
            electricity_tax_ct_kwh=Decimal("2.0500"),
            concession_fee_ct_kwh=Decimal("1.6600"),
            kwk_levy_ct_kwh=Decimal("0.2750"),
            special_grid_levy_ct_kwh=Decimal("0.6430"),
            offshore_levy_ct_kwh=Decimal("0.6560"),
            vat_percent=Decimal("19.00"),
        )

    initial_mfg = [
        ("sungrow", "Sungrow (iSolarCloud)", 15, 10, "iSolarCloud OpenAPI erlaubt bis zu 10s Abfrageintervall."),
        ("huawei", "Huawei (FusionSolar)", 60, 30, "FusionSolar OpenAPI - Limit: 100 API-Aufrufe/Std. empfohlen."),
        ("solaredge", "SolarEdge (Monitoring API)", 60, 30, "SolarEdge Monitoring API - Limit: 300 Aufrufe/Tag."),
        ("fronius", "Fronius (Solarweb API)", 60, 20, "Solarweb API v1 / Realtime Telemetrie."),
        ("sma", "SMA (Sunny Portal / WebConnect)", 30, 15, "SMA WebConnect / Sunny Portal REST API."),
        ("kostal", "Kostal (Solar Portal)", 60, 20, "Kostal Solar Portal REST Schnittstelle."),
        ("deye", "Deye / Solarman", 60, 30, "Solarman Business API v2."),
        ("goodwe", "GoodWe (SEMS Portal)", 60, 30, "GoodWe SEMS Cloud API."),
        ("growatt", "Growatt (ShineServer)", 60, 30, "Growatt OpenAPI v1."),
        ("victron", "Victron Energy (VRM API)", 30, 15, "Victron VRM REST API."),
        ("solis", "Solis / Ginlong Cloud", 60, 30, "SolisCloud OpenAPI v1."),
        ("shelly", "Shelly (Cloud API / Pro EM)", 15, 5, "Shelly Cloud REST API / WebSocket."),
        ("enphase", "Enphase (Enlighten API)", 60, 30, "Enphase Enlighten API v4."),
        ("foxess", "FoxESS Cloud", 60, 30, "FoxESS Open API."),
        ("alphaess", "AlphaESS Cloud", 60, 30, "AlphaESS Open API."),
        ("generic", "Allgemeiner Standard / Fallback", 60, 15, "Allgemeiner Standard-Lesezyklus für nicht spezifizierte Profile."),
    ]

    for key, name, interval, min_int, notes in initial_mfg:
        InverterManufacturerPollingConfig.objects.get_or_create(
            manufacturer_key=key,
            defaults={
                "manufacturer_name": name,
                "polling_interval_seconds": interval,
                "min_allowed_interval_seconds": min_int,
                "rate_limit_notes": notes,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0007_loadpriorityconfig_loadconsumerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMSGlobalSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_grid_price_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('32.00'), help_text='Allgemeiner Standard-Stromarbeitspreis in ct/kWh (brutto) bei Festpreisen', max_digits=6, verbose_name='Standard-Arbeitspreis Netzbezug (ct/kWh)')),
                ('default_feed_in_tariff_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('8.20'), help_text='Standardmäßige Vergütung für eingespeisten PV-Strom gem. EEG (z. B. 8,20 ct/kWh)', max_digits=6, verbose_name='Standard-EEG-Einspeisevergütung (ct/kWh)')),
                ('default_spot_markup_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Anbieter-Aufschlag auf den EPEX Spotpreis in ct/kWh', max_digits=6, verbose_name='Spotmarkt-Aufschlag / Marge (ct/kWh)')),
                ('spot_floor_price_ct_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Untergrenze für dynamischen Strompreis in ct/kWh', max_digits=6, null=True, verbose_name='Spotmarkt-Mindestpreis / Floor (ct/kWh)')),
                ('spot_cap_price_ct_kwh', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Preisbremse / Obergrenze in ct/kWh', max_digits=6, null=True, verbose_name='Spotmarkt-Maximalpreis / Cap (ct/kWh)')),
                ('battery_arbitrage_min_spread_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Erforderliche Preisdifferenz zwischen Lade- und Entladefenster, ab der Arbitrage wirtschaftlich ist', max_digits=6, verbose_name='Batterie-Arbitrage Mindest-Spread (ct/kWh)')),
                ('community_sharing_price_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Standard-Bezugspreis für geteilten Solarstrom innerhalb der Gemeinschaft', max_digits=6, verbose_name='Community-Sharing Bezugspreis (ct/kWh)')),
                ('community_producer_payout_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Standard-Auszahlung an Erzeuger für geteilten Solarstrom', max_digits=6, verbose_name='Community Einspeiser-Vergütung (ct/kWh)')),
                ('community_platform_fee_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Betriebsgebühr / Plattform-Umlage pro geteilter kWh', max_digits=6, verbose_name='Community Plattform- & Betriebsumlage (ct/kWh)')),
                ('grid_fee_ct_kwh', models.DecimalField(decimal_places=4, default=Decimal('9.5000'), help_text='Standardmäßige Netznutzungsentgelte', max_digits=8, verbose_name='Netzentgelte (ct/kWh)')),
                ('electricity_tax_ct_kwh', models.DecimalField(decimal_places=4, default=Decimal('2.0500'), help_text='Gesetzliche Stromsteuer (z. B. 2,05 ct/kWh)', max_digits=8, verbose_name='Stromsteuer (ct/kWh)')),
                ('concession_fee_ct_kwh', models.DecimalField(decimal_places=4, default=Decimal('1.6600'), help_text='Konzessionsabgabe an Kommunen', max_digits=8, verbose_name='Konzessionsabgabe (ct/kWh)')),
                ('kwk_levy_ct_kwh', models.DecimalField(decimal_places=4, default=Decimal('0.2750'), help_text='Kraft-Wärme-Kopplungs-Umlage', max_digits=8, verbose_name='KWKG-Umlage (ct/kWh)')),
                ('special_grid_levy_ct_kwh', models.DecimalField(decimal_places=4, default=Decimal('0.6430'), help_text='Sonderkunden-Umlage nach § 19 StromNEV', max_digits=8, verbose_name='§ 19 StromNEV-Umlage (ct/kWh)')),
                ('offshore_levy_ct_kwh', models.DecimalField(decimal_places=4, default=Decimal('0.6560'), help_text='Offshore-Netzanbindungs-Umlage', max_digits=8, verbose_name='Offshore-Netzumlage (ct/kWh)')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Umsatzsteuer / MwSt in Prozent (z. B. 19.00 %)', max_digits=5, verbose_name='Mehrwertsteuer (%)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zuletzt aktualisiert')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
            ],
            options={
                'verbose_name': 'EMS-Globaleinstellung',
                'verbose_name_plural': 'EMS-Globaleinstellungen (Preise & Tarife)',
                'db_table': 'energy_ems_global_settings',
            },
        ),
        migrations.CreateModel(
            name='InverterManufacturerPollingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manufacturer_key', models.CharField(choices=[('sungrow', 'Sungrow (iSolarCloud)'), ('huawei', 'Huawei (FusionSolar)'), ('solaredge', 'SolarEdge (Monitoring API)'), ('fronius', 'Fronius (Solarweb API)'), ('sma', 'SMA (Sunny Portal / WebConnect)'), ('kostal', 'Kostal (Solar Portal)'), ('deye', 'Deye / Solarman'), ('goodwe', 'GoodWe (SEMS Portal)'), ('growatt', 'Growatt (ShineServer)'), ('victron', 'Victron Energy (VRM API)'), ('solis', 'Solis / Ginlong Cloud'), ('shelly', 'Shelly (Cloud API / Pro EM)'), ('enphase', 'Enphase (Enlighten API)'), ('foxess', 'FoxESS Cloud'), ('alphaess', 'AlphaESS Cloud'), ('generic', 'Allgemeiner Standard / Fallback')], help_text='Eindeutiger Schlüssel des Wechselrichter-Herstellers', max_length=64, unique=True, verbose_name='Hersteller / System-Schlüssel')),
                ('manufacturer_name', models.CharField(help_text='Vollständiger Name des Herstellers / Portals', max_length=150, verbose_name='Herstellername (Anzeige)')),
                ('polling_interval_seconds', models.PositiveIntegerField(default=60, help_text='Abfrageintervall der Hersteller-API in Sekunden (z. B. 15s bei Sungrow, 60s bei Huawei)', verbose_name='Lesezyklus (Sekunden)')),
                ('min_allowed_interval_seconds', models.PositiveIntegerField(default=10, help_text='Sicherheits-Untergrenze, um API-Sperren / Rate-Limits zu verhindern', verbose_name='Min. zulässiges Intervall (Sekunden)')),
                ('rate_limit_notes', models.CharField(blank=True, default='', help_text="z. B. 'Max. 100 Anfragen / Std.' oder 'OpenAPI Token erforderlich'", max_length=255, verbose_name='Rate-Limit Hinweise & API-Limits')),
                ('is_active', models.BooleanField(default=True, help_text='Steuert, ob Integrationen dieses Herstellers periodisch gepollt werden', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WR-Hersteller Lesezyklus',
                'verbose_name_plural': 'WR-Hersteller Lesezyklen (API-Polling)',
                'db_table': 'energy_inverter_manufacturer_polling_config',
                'ordering': ['manufacturer_name'],
            },
        ),
        migrations.RunPython(seed_initial_ems_settings, migrations.RunPython.noop),
    ]
