# Generated by Django on 2026-09-07

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0008_emsglobalsettings_invertermanufacturerpollingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emsglobalsettings',
            name='landlord_monthly_price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('14.99'), help_text='Monatlicher Preis für Vermieter & Mehrparteien-Gebäude inkl. MwSt.', max_digits=6, verbose_name='Vermieter & Quartiere (Monatlich - € brutto)'),
        ),
        migrations.AddField(
            model_name='emsglobalsettings',
            name='landlord_yearly_price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('149.99'), help_text='Jährlicher Preis für Vermieter & Mehrparteien-Gebäude inkl. MwSt.', max_digits=6, verbose_name='Vermieter & Quartiere (Jährlich - € brutto)'),
        ),
        migrations.AddField(
            model_name='emsglobalsettings',
            name='pro_monthly_price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.99'), help_text='Monatlicher Endkundenpreis für das Sharegy Pro SaaS-Abo inkl. MwSt.', max_digits=6, verbose_name='Sharegy Pro (Monatlich - € brutto)'),
        ),
        migrations.AddField(
            model_name='emsglobalsettings',
            name='pro_yearly_price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('49.99'), help_text='Jährlicher Endkundenpreis für das Sharegy Pro Jahresabonnement inkl. MwSt.', max_digits=6, verbose_name='Sharegy Pro (Jährlich - € brutto)'),
        ),
        migrations.AddField(
            model_name='emsglobalsettings',
            name='saas_pricing_valid_from',
            field=models.DateField(default=django.utils.timezone.now, help_text='Datum, ab dem die konfigurierten Software-Lizenzpreise für Neukunden und Verlängerungen gelten', verbose_name='SaaS-Preise gültig ab'),
        ),
        migrations.AddField(
            model_name='emsglobalsettings',
            name='trial_days',
            field=models.PositiveIntegerField(default=14, help_text='Dauer der kostenlosen Testphase für Sharegy Pro bei Neuanmeldung', verbose_name='Kostenlose Testphase (Tage)'),
        ),
    ]
