# Generated by Django on 2026-09-07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0009_emsglobalsettings_saas_pricing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emsglobalsettings',
            options={'verbose_name': 'EMS-Globaleinstellung', 'verbose_name_plural': 'EMS-Globaleinstellungen (Plattform-Preise & Abgaben)'},
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='battery_arbitrage_min_spread_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='community_platform_fee_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='community_producer_payout_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='community_sharing_price_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='default_feed_in_tariff_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='default_grid_price_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='default_spot_markup_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='spot_cap_price_ct_kwh',
        ),
        migrations.RemoveField(
            model_name='emsglobalsettings',
            name='spot_floor_price_ct_kwh',
        ),
        migrations.AddField(
            model_name='emsglobalsettings',
            name='sharegy_platform_fee_ct_kwh',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Betriebsgebühr / Plattform-Umlage pro geteilter kWh für automatisierte Messdatenerfassung, Clearing und Monatsabrechnungen gem. § 42b EnWG', max_digits=6, verbose_name='Sharegy Plattform-Umlage (ct/kWh)'),
        ),
    ]
