# Generated by Django 6.0.5 on 2026-09-06 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0010_streamline_ems_global_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='griddimmingsignal',
            options={'ordering': ['-started_at'], 'verbose_name': '§ 14a Netz-Dimmsignal', 'verbose_name_plural': '§ 14a Netz-Dimmsignale (Netzbetreiber-Drosselung)'},
        ),
        migrations.AlterModelOptions(
            name='steuvedeviceconfig',
            options={'ordering': ['priority', '-rated_power_kw'], 'verbose_name': '§ 14a SteuVE-Konfiguration', 'verbose_name_plural': '§ 14a SteuVE-Geräte (Steuerbare Verbrauchseinrichtungen)'},
        ),
    ]
