# Generated by Django 6.0.5 on 2026-09-07 19:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_alter_clouddeviceintegration_polling_interval_seconds'),
        ('energy', '0011_alter_griddimmingsignal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadconsumerconfig',
            name='category',
            field=models.CharField(choices=[('pool', 'Pool- & Filterpumpe'), ('ac', 'Klimaanlage / Raumkühlung'), ('floor_heating', 'Fußbodenheizung & Estrich-Speicher'), ('appliances', 'Haushaltsgerät (Waschmaschine/Spüler)'), ('heating_rod', 'Heizstab / Power-to-Heat'), ('bwwp', 'Brauchwasserwärmepumpe'), ('wallbox', 'Wallbox / E-Auto'), ('battery', 'Heimspeicher'), ('other', 'Sonstiger flexibler Verbraucher')], default='pool', max_length=20),
        ),
        migrations.CreateModel(
            name='FloorHeatingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('control_mode', models.CharField(choices=[('autopilot', 'Autopilot (Solar- & Börsenpreis-Vorladung)'), ('pv_only', 'Nur PV-Überschuss'), ('price_saver', 'Sparfuchs (Günstigste Börsenstunden)'), ('comfort', 'Komfortbetrieb (Feste Solltemperatur)'), ('manual', 'Manuell')], default='autopilot', max_length=20)),
                ('target_room_temp_c', models.DecimalField(decimal_places=1, default=Decimal('21.0'), help_text='Standard-Zieltemperatur im Raum (°C)', max_digits=4)),
                ('boost_delta_k', models.DecimalField(decimal_places=1, default=Decimal('1.0'), help_text='Thermische Vorladung / Überwärmungs-Delta (+K, z. B. +1,0°C bei Überschuss)', max_digits=3)),
                ('max_floor_temp_c', models.DecimalField(decimal_places=1, default=Decimal('24.5'), help_text='Überhitzungsschutz: Maximale Raum-/Estrich-Temperatur (°C)', max_digits=4)),
                ('min_pv_surplus_w', models.DecimalField(decimal_places=1, default=Decimal('1000.0'), help_text='Mindest-Solarüberschuss (W) für automatische Vorladung', max_digits=6)),
                ('max_spot_price_ct_kwh', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='Maximaler Strompreis (ct/kWh) für netzbasierte Vorladung', max_digits=5)),
                ('estrich_area_sqm', models.DecimalField(decimal_places=1, default=Decimal('120.0'), help_text='Beheizte Estrich-Fläche in m² zur Kapazitätsberechnung', max_digits=6)),
                ('is_preheating_active', models.BooleanField(default=False, help_text='Gibt an, ob aktuell eine thermische Vorladung aktiv ist')),
                ('last_switched_at', models.DateTimeField(blank=True, null=True)),
                ('min_run_minutes', models.PositiveIntegerField(default=30, help_text='Mindestlaufzeit (Min) zur Vermeidung von Pumpen-/Ventiltakten')),
                ('min_rest_minutes', models.PositiveIntegerField(default=15, help_text='Mindestruhezeit (Min) vor erneutem Einschalten')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, help_text='Heizkreispumpe, Shelly Relais oder Stellantrieb-Aktor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_heating_controllers', to='devices.device')),
                ('home', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='floor_heating_config', to='devices.home')),
                ('temp_sensor_device', models.ForeignKey(blank=True, help_text='Temperatursensor im Referenzraum oder Estrich-Fühler', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='floor_heating_sensors', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
