# Generated by Django 6.0.5 on 2026-09-07 19:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0012_alter_loadconsumerconfig_category_floorheatingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorheatingconfig',
            name='heating_curve_slope',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.60'), help_text='Heizkurven-Steilheit für Fußbodenheizung (typisch 0.4 bis 0.8)', max_digits=3),
        ),
        migrations.AddField(
            model_name='floorheatingconfig',
            name='predictive_mpc_enabled',
            field=models.BooleanField(default=True, help_text='Aktiviert KI-Wetter-Vorhersagen & dynamische Vorlauf-Optimierung (MPC)'),
        ),
        migrations.AddField(
            model_name='floorheatingconfig',
            name='solar_gain_compensation',
            field=models.BooleanField(default=True, help_text='Automatische Vorlaufabsenkung bei starker prognostizierter Sonneneinstrahlung'),
        ),
    ]
