# Generated by Django 6.0.5 on 2026-09-09 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0044_chargingsession_v2g_discharged_kwh_and_more'),
        ('energy', '0013_floorheatingconfig_heating_curve_slope_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnWG14aDimmingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('DIMMING_TRIGGERED', 'Dimmsignal empfangen & aktiviert'), ('DEVICE_DIMMED', 'SteuVE-Leistung gedrosselt'), ('DEVICE_RESTORED', 'SteuVE-Drosselung aufgehoben'), ('LIMIT_CLEARED', 'Netzdrosselung beendet'), ('COMPLIANCE_VERIFIED', '4,2 kW Compliance am Netzanschlusspunkt bestätigt'), ('OVERRIDE_REJECTED', 'Manueller Eingriff abgewiesen (Netzsicherheitsvorrang)')], db_index=True, max_length=40)),
                ('steuve_type', models.CharField(blank=True, default='', max_length=30)),
                ('commanded_power_limit_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('power_before_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('power_after_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pv_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('battery_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grid_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Aktor-Reaktionszeit in Millisekunden (Nachweis der < 30s Frist)')),
                ('compliance_verified', models.BooleanField(default=True, help_text='Gesetzliches 4,2 kW Netzkontingent am Netzanschlusspunkt eingehalten')),
                ('vnb_operator_id', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enwg_dimming_audit_logs', to='devices.device')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enwg_dimming_audit_logs', to='devices.home')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='energy.griddimmingsignal')),
            ],
            options={
                'verbose_name': '§ 14a EnWG Dimm-Audit-Log',
                'verbose_name_plural': '§ 14a EnWG Dimm-Audit-Logs (Revisionsnachweis)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['home', '-created_at'], name='energy_enwg_home_id_45cdd0_idx'), models.Index(fields=['action', '-created_at'], name='energy_enwg_action_ed5c32_idx'), models.Index(fields=['compliance_verified', '-created_at'], name='energy_enwg_complia_d4b854_idx')],
            },
        ),
    ]
