# Generated by Django 6.0.5 on 2026-08-31 02:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0038_devicebaselineprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True, help_text='Globale Push-Aktivierung für diesen Account')),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Benachrichtigungen zu bestimmten Uhrzeiten stummschalten')),
                ('quiet_hours_start', models.TimeField(default='22:00:00', help_text='Beginn der Nachtruhe (z. B. 22:00)')),
                ('quiet_hours_end', models.TimeField(default='07:00:00', help_text='Ende der Nachtruhe (z. B. 07:00)')),
                ('allow_critical_in_quiet_hours', models.BooleanField(default=True, help_text='Kritische Notfall-Alarme (z. B. Speicher leer, Frost) trotz Ruhezeit zustellen')),
                ('notify_battery', models.BooleanField(default=True, help_text='Speicher-Notreserve & Entlade-Warnungen')),
                ('notify_leakage', models.BooleanField(default=True, help_text='Nachtverbrauch & Dauerlast-Leckagen')),
                ('notify_pv', models.BooleanField(default=True, help_text='PV-Ausfall & Ertragsanomalien')),
                ('notify_prices', models.BooleanField(default=True, help_text='Börsenstrom-Negativpreise & Preis-Peaks')),
                ('notify_device_status', models.BooleanField(default=True, help_text='Geräte-Offline & Signal-Verlust')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(choices=[('web_push', 'Web-Push (Safari / Chrome / Firefox)'), ('ios', 'iOS (Apple APNs)'), ('android', 'Android (Google FCM)')], default='web_push', max_length=32)),
                ('endpoint', models.URLField(blank=True, default='', max_length=1024)),
                ('p256dh_key', models.CharField(blank=True, default='', max_length=255)),
                ('auth_key', models.CharField(blank=True, default='', max_length=255)),
                ('fcm_token', models.CharField(blank=True, default='', max_length=1024)),
                ('device_name', models.CharField(blank=True, default='', help_text="z. B. 'iPhone 15 Pro', 'Pixel 8', 'Chrome auf Windows'", max_length=128)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_subscriptions', to='devices.home')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_c17775_idx'), models.Index(fields=['home', 'is_active'], name='notificatio_home_id_27b26c_idx'), models.Index(fields=['endpoint'], name='notificatio_endpoin_f9b95a_idx')],
            },
        ),
    ]
