# Generated by Django 6.0.5 on 2026-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesubscription',
            name='registered_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP-Adresse bei Aktivierung', null=True),
        ),
        migrations.AddField(
            model_name='devicesubscription',
            name='unregistered_at',
            field=models.DateTimeField(blank=True, help_text='Zeitpunkt der Deaktivierung', null=True),
        ),
        migrations.AddField(
            model_name='devicesubscription',
            name='unregistered_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP-Adresse bei Deaktivierung', null=True),
        ),
    ]
